# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Easy_Parking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Easy_Parking
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'


  target 'Easy_ParkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Easy_ParkingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
